version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "patch"
  - package-ecosystem: "cargo"
    directory: "/api"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "patch"