version: "3.9"
services:
  db:
    container_name: "la-beuverie-db"
    image: "mongo"
    restart: "always"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "password"
      MONGO_INITDB_DATABASE: "la-beuverie"
    ports:
      - "27017:27017"
  api:
    container_name: "la-beuverie-api"
    build: "api"
    ports:
      - "8000:8000"
    depends_on:
      - db
  client:
    container_name: "la-beuverie-client"
    build: "client"
    ports:
      - "3000:3000"
    depends_on:
      - api
