services:
  db:
    image: postgres:alpine
    container_name: db
    shm_size: 128mb
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: 'La-beuverie'
