[package]
name = "la-beuverie"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
jsonwebtoken = "9.1.0"
mongodb = "2.7.0"
bson = { version = "2", features = ["chrono-0_4"] }
chrono = "0.4.31"
serde = "1.0.190"
futures = { version = "0.3.29", features = [] }
uuid = "1.5.0"
serde_json = "1.0.108"
argon2 = "0.5.2"
dotenv = "0.15.0"