[package]
name = "la-beuverie"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
mongodb = "2.7.0"
bson = { version = "2", features = ["chrono-0_4"] }
chrono = "0.4.31"
serde = "1.0.190"
serde_json = { version = "1.0.108", features = [] }
futures = { version = "0.3.29", features = [] }
