name: API build
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
	  - uses: actions/setup-rust@v1
	    with:
	      rust-version: 'stable'
    - run: cargo build --release
