name: Client build
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependancies
        working-directory: ./client
        run: bun install

      - name: Build project
        working-directory: ./client
        run: bun build

      - name: Lint project
        working-directory: ./client
        run: bun run format && bun run lint
