name: Lighthouse
on:
  pull_request:
    branches: [ "main" ]
jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm install && npm install -g @lhci/cli@0.12.x
        working-directory: ./client
      - run: npm run build
        working-directory: ./client
      - run: lhci autorun
        working-directory: ./client
