name: Rust
on:
  pull_request:
    branches: [ "main" ]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    steps:
    - uses: actions/checkout@v3
    - name: Build
      working-directory: ./api
      run: cargo build --verbose
    - name: Run tests
      working-directory: ./api
      run: cargo test --verbose
  dependabot:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: actions/checkout@v3
      - name: Build
        if: steps.metadata.outputs.package-ecosystem == 'cargo'
        working-directory: ./api
        run: cargo build --verbose
      - name: Run tests
        if: steps.metadata.outputs.package-ecosystem == 'cargo'
        working-directory: ./api
        run: cargo test --verbose
  
