on:
  push:
    branches: [main]

name: Create Release

permissions:
  pull-requests: write
  issues: write
  repository-projects: write

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: paulhatch/semantic-version@v5.3.0
        with:
          tag_prefix: "v"
          major_pattern: "(MAJOR|BREAKING)"
          major_regexp_flags: ""
          minor_pattern: "(MINOR|FEAT)"
          minor_regexp_flags: ""
          version_format: "${major}.${minor}.${patch}"
          bump_each_commit: false
          search_commit_body: false
          user_format_type: "json"
          version_from_branch: false